// Frontend/vuejs/src/components/Entries.vue
<template>
    <div class="entries">
        <Entry 
            v-for="entry in EntryStore.entries" 
            v-bind:key="entry.id" 
            v-bind:entry="entry" 
            />

        <h3 v-if="EntryStore.entries.length === 0">Nic tutaj nie ma ;(</h3>
    </div>
</template>

<script>
import Entry from "./Entry.vue";
import EntryStore from "@/store/EntryStore.js";

export default {
  name: "Entries",
  components: { Entry },
  data() {
    return {
      EntryStore: EntryStore.data
    };
  },
  async created() {
    await EntryStore.methods.updateList();
  }
};
</script>

// Frontend/nanoblog/src/components/entries.jsx
import React, { Component } from "react";

import Entry from "./entry";

class Entries extends Component {
  getEnteries() {
    if (this.props.entries.length > 0) {
      return this.props.entries.map(entry => (
        <Entry
          key={entry.id}
          auth={this.props.auth}
          author={entry.author}
          date={entry.createTime}
          dataKey={entry.id}
          onDelete={this.props.onDelete}
        >
          {entry.text}
        </Entry>
      ));
    } else {
      return <h3>Nic tutaj nie ma ;(</h3>;
    }
  }

  render() {
    if (this.props.isLoaded) return this.getEnteries();
    else return <h3>Ładowanie...</h3>;
  }
}

export default Entries;
