// Frontend/nanoblog/src/components/add-entry.jsx
import React, { Component } from "react";

import "./add-entry.css";

class AddEntry extends Component {
  state = {
    text: ""
  };

  handleChange = event => {
    this.setState({ text: event.target.value });
  };

  handleSubmit = event => {
    event.preventDefault();

    this.props.onSubmit(this.state.text);

    this.setState({ text: "" });
  };

  render() {
    return (
      <React.Fragment>
        <h3>Dodaj post</h3>
        <form onSubmit={this.handleSubmit}>
          <div className="form-group">
            <textarea
              value={this.state.text}
              onChange={this.handleChange}
              id="input-text-form"
              rows="5"
            />
          </div>

          <button type="submit" className="btn btn-primary">
            Dodaj
          </button>
        </form>
      </React.Fragment>
    );
  }
}

export default AddEntry;

// Frontend/vuejs/src/components/AddEntry.vue
<template>
    <div>
        <h3>Dodaj post</h3>
        <form @submit="addEntry">
          <div class="form-group">
            <textarea
              id="input-text-form"
              rows="5"
              v-model="entryText"
            />
          </div>

          <button type="submit" class="btn btn-primary">
            Dodaj
          </button>
        </form>
    </div>
</template>

<script>
import EntryStore from "@/store/EntryStore.js";

export default {
  data() {
    return {
      entryText: ""
    };
  },
  methods: {
    async addEntry(e) {
      e.preventDefault();

      try {
        let result = await EntryStore.methods.addEntry(this.entryText);
        EntryStore.methods.updateList();
      } catch (exc) {
        console.log(exc.response);
      }

      this.entryText = "";
    }
  }
};
</script>

<style scoped>
#input-text-form {
  width: 100%;
}
</style>
