// Frontend/nanoblog/src/components/navbar.jsx
import React, { Component } from "react";

import "./navbar.css";

class Navbar extends Component {
  state = {
    userInfo: {},
    isLoaded: false
  };

  componentDidMount() {
    var userId = this.props.auth.getUserId();
    this.setState({ isLoaded: false });

    if (userId !== null) {
      fetch("/api/accounts/user/" + userId).then(response => {
        if (response.ok) {
          response.json().then(json => {
            this.setState({ userInfo: json, isLoaded: true });
          });
        }
      });
    }
  }

  render() {
    return (
      <nav className="navbar navbar-expand navbar-dark bg-dark">
        <a className="navbar-brand" href="">
          Nanoblog
        </a>
        <button
          className="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon" />
        </button>
        <div className="collapse navbar-collapse">
          <ul className="navbar-nav mr-auto">
            <li className="nav-item active">
              <a className="nav-link" href="">
                Nanoblog
                <span className="sr-only">(current)</span>
              </a>
            </li>
          </ul>
        </div>

        {this.renderLoginButton()}
      </nav>
    );
  }

  renderLoginButton() {
    let button = null;

    if (this.props.auth.isAuthenticated()) {
      var welcome;

      if (this.state.isLoaded) {
        welcome = (
          <span className="navbar-text user-welcome">
            Witaj, <a href="">{this.state.userInfo.userName}</a>
          </span>
        );
      }

      button = (
        <React.Fragment>
          {welcome}

          <button
            className="btn btn-secondary"
            onClick={() => this.props.auth.logout()}
          >
            Logout
          </button>
        </React.Fragment>
      );
    } else {
      button = (
        <React.Fragment>
          <button
            className="btn btn-secondary"
            onClick={() => (document.location.href = "/register")}
          >
            Register
          </button>
          <button
            className="btn btn-secondary"
            onClick={() => (document.location.href = "/login")}
          >
            Login
          </button>
        </React.Fragment>
      );
    }

    return button;
  }
}

export default Navbar;

// Frontend/vuejs/src/components/NavBar.vue
<template>
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="">
        Nanoblog
    </a>
    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon" />
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <router-link to="/" class="nav-link">Nanoblog <span class="sr-only">(current)</span></router-link>
        </li>
        </ul>
    </div>

    <span v-if="UserStore.auth.isAuthenticated">
        <span v-if="UserStore.user.isLoaded">
            <span class="navbar-text user-welcome">
                Witaj, <a href="">{{UserStore.user.userName}}</a>
            </span>
            <button v-on:click="onLogout" class="btn btn-secondary"> Logout</button>
        </span>
        <span v-if="UserStore.user.isLoaded == false" class="navbar-text">
            Ładowanie...
        </span>
    </span>
    <span v-else>
        <router-link to="/login" class="btn btn-secondary" tag="button">Login</router-link>
        <router-link to="/register" class="btn btn-secondary" tag="button">Register</router-link>
    </span>
</nav>
</template>

<script>
import UserStore from "@/store/UserStore.js";

export default {
  data() {
    return {
      UserStore: UserStore.data
    };
  },
  methods: {
    async onLogout() {
      await UserStore.methods.logout();
    }
  }
};
</script>


<style scoped>
.user-welcome {
  margin-right: 16px;
}
</style>
