// Frontend/vuejs/src/views/Register.vue
<template>
<form v-on:submit="handleSubmit">
    <div v-if="errorMsg.length > 0" class="alert alert-danger" role="alert">
        {{errorMsg}}
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <input
        type="email"
        class="form-control"
        name="email"
        placeholder="E-mail"
        v-model="email"
        />
    </div>
    <div class="form-group">
        <label>Nazwa użytkownika</label>
        <input
        type="text"
        class="form-control"
        name="username"
        placeholder="Nazwa użytkownika"
        v-model="username"
        />
    </div>
    <div class="form-group">
        <label>Hasło</label>
        <input
        type="password"
        class="form-control"
        name="password"
        placeholder="Hasło"
        v-model="password"
        />
    </div>

    <button type="submit" class="btn btn-primary" name="submit">
        Zarejestruj się
    </button>
</form>
</template>

<script>
import AccountApi from "@/api/AccountApi";
import router from "@/router";

export default {
  data() {
    return {
      email: "",
      username: "",
      password: "",
      errorMsg: ""
    };
  },
  methods: {
    async handleSubmit(e) {
      e.preventDefault();

      try {
        var data = await AccountApi.register(
          this.email,
          this.username,
          this.password
        );

        router.push({ name: "login" });
      } catch (ex) {
        this.errorMsg = ex.response.data.message;
      }
    }
  }
};
</script>

// Frontend/nanoblog/src/views/Register.jsx
import React, { Component } from "react";

class Register extends Component {
  state = {
    email: "",
    username: "",
    password: ""
  };

  handleUserInput = e => {
    const name = e.target.name;
    const value = e.target.value;
    this.setState({ [name]: value });
  };

  handleFormSubmit = event => {
    event.preventDefault();

    console.log(JSON.stringify(this.state));

    fetch("/api/accounts/register", {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json"
      },
      method: "POST",
      body: JSON.stringify(this.state)
    })
      .then(res => res.json())
      .then(result => {
        console.log(result);
      });
  };

  render() {
    return (
      <form onSubmit={this.handleFormSubmit}>
        <div className="form-group">
          <label>E-mail</label>
          <input
            type="email"
            className="form-control"
            name="email"
            value={this.state.email}
            onChange={event => this.handleUserInput(event)}
            placeholder="E-mail"
          />
        </div>
        <div className="form-group">
          <label>Nazwa użytkownika</label>
          <input
            type="text"
            className="form-control"
            name="username"
            value={this.state.username}
            onChange={event => this.handleUserInput(event)}
            placeholder="Nazwa użytkownika"
          />
        </div>
        <div className="form-group">
          <label>Hasło</label>
          <input
            type="password"
            className="form-control"
            name="password"
            value={this.state.password}
            onChange={event => this.handleUserInput(event)}
            placeholder="Hasło"
          />
        </div>

        <button type="submit" className="btn btn-primary" name="submit">
          Zarejestruj się
        </button>
      </form>
    );
  }
}

export default Register;
